# Generated by Django 3.0.5 on 2020-04-06 19:55

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('expense_type', models.CharField(choices=[('invoice', 'Invoice'), ('salary', 'Salary'), ('services', 'Services'), ('office-supplies', 'Office supplies'), ('travel', 'Travel')], max_length=15)),
                ('account_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=255)),
            ],
        ),
    ]
