# Generated by Django 3.0.5 on 2020-04-07 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transaction_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
